describe('template spec', () => {
  it('passes', () => {
    cy.visit('/', { failOnStatusCode: false })
    cy.contains('Sign In').click()
    cy.url().should('include', '/sign-in')
    cy.get('input[name="identifier"]').type('cypress')
    cy.get('button.cl-formButtonPrimary').click()
    cy.get('input[name="password"]').type('option123')
    cy.get('button.cl-formButtonPrimary').click()
    cy.wait(1000)
    cy.visit('/products/all', { failOnStatusCode: false })
    cy.wait(1000)
    cy.get('header div.hidden button[test-id="cart-button"]').click()
    cy.wait(400)
    cy.get('button[test-id="cart-close-button"]').click()
    cy.wait(400)
    cy.contains(/\Add to cart\b/).click()
    cy.get('header div.hidden button[test-id="cart-button"]').click()
    cy.get('button[test-id="checkout-button"]').click({ timeout: 7000 })
    cy.contains('Select country').should('be.visible')
    cy.contains('Select country').click()
    cy.contains('Latvia').click()
    cy.contains('Omniva Parcel').click()
    cy.get('input[name="shippingAddress.phoneNumber"]').type('12345678')
    cy.contains('Select parcel machine').should('be.visible').click()
    cy.contains('Salaspils RIMI').click()
    cy.contains(/\Continue to payment\b/).click()
    cy.wait(5000)
    cy.url().should('not.include', 'localhost')
  })
})